version: "3.8"
services:

  react-app:
    container_name: react-app-dev
    restart: always
    build:
      context: ./frontend # Directory where the React app is located
      dockerfile: Dockerfile.dev
    volumes:
       - ./frontend:/app:delegated
       - /node_modules
    ports:
      - "3000:3000"
    # environment:
    #    - CHOKIDAR_USEPOLLING=true
    networks:
      - my_network

  backend:  
    container_name: backend-dev
    build:
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  
    depends_on:
      - react-app
    networks:
      - my_network

  nginx:
    image: frontendreactapp.azurecr.io/nginx
    depends_on:
      - react-app
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
    networks:
      - my_network

networks:
  my_network:
